### ISSUE TITLE
Q: Bootstrap 5 Support planned?

### ISSUE THREAD

**Issue by simialbi** [kartik-v/yii2-krajee-base#113]
Hi @kartik-v 

Thanks for your great work. Is a bootstrap 5 support planned?

**Comment by fusivel** [comment]
Hi @simialbi and Hi @kartik-v —> Thanks for your great work. 

Is a bootstrap 5 support planned? 
I would like It too, by the way:
curiously I Looked at this file -> yii2-krajee-base/src/BootstrapTrait.php from line 180 :

-> $ext = 'bootstrap' . ($this->_isBs4 ? '4' : '');

if we change 4 to 5  -> $ext = 'bootstrap' . ($this->_isBs4 ? '5' : '');

apparently  everything seam to be working, visualy only some css get messed.

could be a start?

Thanks

**Comment by muitosefala** [comment]
Hi @simialbi and Hi @kartik-v —> Thanks for your great work.

Is a bootstrap 5 support planned?
I would like It too, by the way:
curiously I Looked at this file -> yii2-krajee-base/src/BootstrapTrait.php from line 180 :

-> $ext = 'bootstrap' . ($this->_isBs4 ? '4' : '');

if we change 4 to 5 -> $ext = 'bootstrap' . ($this->_isBs4 ? '5' : '');

apparently everything seam to be working, visualy only some css get messed.

could be a start?

Thanks

**Comment by kartik-v** [comment]
Will need to look and check this - because the yii2-bootstrap library for BS v5.x does not exist for yii2 and is only there in yii3 - it requires rework on few of the BS5 components which have changed like Modal.

**Comment by muitosefala** [comment]
> Will need to look and check this - because the yii2-bootstrap library for BS v5.x does not exist for yii2 and is only there in yii3 - it requires rework on few of the BS5 components which have changed like Modal.
@kartik-v , check this:
https://github.com/yiisoft/yii2-bootstrap5

**Comment by muitosefala** [comment]
@kartik-v  you could create a new Bs5 branch so we could help, maybe?

**Comment by kartik-v** [comment]
Thanks will initiate this soon.

**Comment by kartik-v** [comment]
I have created a new branch `bootstrap-5` and will try to set that branch up with some initial updates
