### ISSUE TITLE
Datepicker Format-Error because of Lib::substr and PHP lower 8

### ISSUE THREAD

**Issue by DSTester** [kartik-v/yii2-krajee-base#118]
https://github.com/kartik-v/yii2-krajee-base/blob/9de9f028119e571f51bc8c7b98618648a7249070/src/InputWidget.php#L305

Version: 3.0.3
PHP: 7.4
Used with: kartik-v/yii2-widget-datepicker

The usage of Version 3.0.3 of this package in an environment with PHP Version lower 8.0 results in an empty format-String. So the Datepicker doesn't open in the Browser and logs an error: `Uncaught Error: Invalid date format.`
Prior to PHP 8 `substr()`, which is used in `Lib::substr()`, returns an empty string if `length` is `null`.

I fixed this by adding `"kartik-v/yii2-krajee-base": "3.0.2",` to my composer.json.

**Comment by papppeter** [comment]
It happened the same to me.
