### ISSUE TITLE
Default script position in WidgetTrait.php

### ISSUE THREAD

**Issue by josebarturen** [kartik-v/yii2-krajee-base#32]
Hi,
There is an explicit View::POS_HEAD in the following file. I think this could be read from the AppAsset config file, or by default View::POS_READY.
Thanks

/vendor/kartik-v/yii2-krajee-base/WidgetTrait.php 
Line 86 
Original Line: $view->registerJs("var {$this->_hashVar} = {$encOptions};\n", View::POS_HEAD);
New Line: $view->registerJs("var {$this->_hashVar} = {$encOptions};\n", View::POS_READY);

**Comment by kartik-v** [comment]
No this is intentional by design. The script position HAS to BE View::POS_HEAD - so that the same options can be used by all widget plugins on the same page (especially if there are multiple plugins with same options on the same page like tabular data).
