### ISSUE TITLE
Json::htmlEncode

### ISSUE THREAD

**Issue by nkovacs** [kartik-v/yii2-krajee-base#38]
You should use `Json::htmlEncode` instead of `Json::encode` when the result is inserted into html.

For example, here: https://github.com/kartik-v/yii2-krajee-base/blob/master/WidgetTrait.php#L71

More info: http://www.yiiframework.com/news/86/yii-2-0-4-is-released/

**Comment by kartik-v** [comment]
No it cannot be used for WidgetTrait... since only `Json::encode` allows encoding of `JsExpression`.

**Comment by kartik-v** [comment]
Will need to check on this... and update.

**Comment by nkovacs** [comment]
Select2's tags may contain user input. I can't Html encode them, because select2 expects them to not be encoded, so they have to be Json::htmlEncode-ed to be correctly passed to select2.

**Comment by kartik-v** [comment]
Resolved via latest commit.

**Comment by cappato** [comment]
hi, i finish to implement upgrade 2.0.2 to 2.0.5 last version, so then i paste the new vendor version in my project and install again the kartik nav navx and now i have this error in one page
 Call to undefined method yii\helpers\Json::htmlEncode()
help please.

**Comment by cappato** [comment]
finally i installed the new version in a new project, all widgets again, create the modules  migrate the models, controllers, views and assets. This fix mi problem. thx

**Comment by kartik-v** [comment]
Yes you must install via composer... and not manually copy paste files... else you will get errors because of package dependencies.

**Comment by cappato** [comment]
you say upgrade yii 2.0.2 to 2.0.5 via composer? is posible this? I not found any code to do this

**Comment by kartik-v** [comment]
I was talking about updating this extension. 

But yes you can also update yii via composer using `composer update`. Refer composer docs to configure your composer.json if you are unclear.

**Comment by cappato** [comment]
Ok. Thank you again Kartik
