### ISSUE TITLE
Call to undefined method yii\helpers\Json::htmlEncode()

### ISSUE THREAD

**Issue by dzona** [kartik-v/yii2-krajee-base#39]
Please change ``Json::htmlEncode()`` to valid method name 
L#71 WidgetTrait.php

**Comment by kartik-v** [comment]
Read related #38. You need to update to latest release of yii v2.0.4.

**Comment by skugarev** [comment]
Call to undefined method kartik\tabs\TabsXAsset::registerBundle()
