### ISSUE TITLE
InputWidget.php

### ISSUE THREAD

**Issue by rochdi80tn** [kartik-v/yii2-krajee-base#43]
## Issue description
When you create a DateControl widget on an active field with a specefic value, your value is not taken into account later by the InputWidget init() function.
Example  
```php
echo $form->field($model, 'some_date')->widget(DateControl::classname(), [
    'type'=> DateControl::FORMAT_DATE,
    'value'=> '2015-02-25',
    'displayFormat' => 'php:d/M/Y',
    'saveFormat' => 'php:Y-m-d',
]);
```
The value `2015-02-25` is simply ignored and the actual `$model->some_date` value is being taken.

## Suggestion to fix this 

In the `public function init()`  of `class InputWidget extends \yii\widgets\InputWidget `  change the following lline #45
```php
$this->value = Html::getAttributeValue($this->model, $this->attribute);
```
to 
```php
$this->value = $this->value===null? Html::getAttributeValue($this->model, $this->attribute) : $this->value;
```
This will check whether the value property is already set or not, and if not then load its value from the model attribute

**Comment by kartik-v** [comment]
This is not the intended method to do it... you may want to check Yii core Documentation. For input widgets WITH MODEL - the value is derived directly from MODEL ATTRIBUTE - no VALUE property is parsed.

THIS IS WRONG (which you are doing)
```php
echo $form->field($model, 'some_date')->widget(DateControl::classname(), [
    'type'=> DateControl::FORMAT_DATE,
    'value'=> '2015-02-25',
    'displayFormat' => 'php:d/M/Y',
    'saveFormat' => 'php:Y-m-d',
]);
```

THIS IS RIGHT...
(INSTEAD YOU MUST DO THIS)

```php
// your initial value must be set in model attribute
$model->some_date = '2015-02-25',

echo $form->field($model, 'some_date')->widget(DateControl::classname(), [
    'type'=> DateControl::FORMAT_DATE,
    'displayFormat' => 'php:d/M/Y',
    'saveFormat' => 'php:Y-m-d',
]);
```

**Comment by rochdi80tn** [comment]
Understand. My point is that I've changed my `$model->some_date` to be an object having an instance  of  `\Datetime` property to hold the date.

When I call `$model->some_date`, the `__toString()` method is returning a well formatted date as per my needs (the `displayFormat`), and this is for use in view pages, listing etc.

If I need to take the say *DB value* I call `$model->some_date->value` where my `getValue()` method is returning the actual DB formated value.

If I switch the two returns the DateControl widget will work fine as when it will try to get the attribute value it will get the correct saveFormat one. But in this case I need to specically call a formatter method for my display places..

So I beleive I'll think of an alternate way..
Thanks for your feedback.
