### ISSUE TITLE
wish(file-input): list style preview or smaller picture box preview

### ISSUE THREAD

**Issue by joomlaA1** [kartik-v/yii2-krajee-base#44]
wish: 
preview like a list style instead of picture box style thanks
(also capable of multi upload, remove one by one thanks)

**Comment by joomlaA1** [comment]
hello @kartik-v

**Comment by joomlaA1** [comment]
hello @kartik-v... how about this..? list style preview...? thanks...

**Comment by kartik-v** [comment]
Please post the issue in the right repo. Closing this.
