### ISSUE TITLE
how to trigger upload when data-show-upload="false"

### ISSUE THREAD

**Issue by joomlaA1** [kartik-v/yii2-krajee-base#45]
how to trigger upload when data-show-upload="false"
is there a method that can be attached to a button? thanks

**Comment by joomlaA1** [comment]
method for "upload" and method for "remove"
able to be attached to jquery on click event of button
thanks

**Comment by joomlaA1** [comment]
hello @kartik-v

**Comment by joomlaA1** [comment]
@dabros could you help me here too? please ... thanks...

its just that.. it has a built in upload button... this file input plugin...
![krajee](https://cloud.githubusercontent.com/assets/13029902/11235426/8b7bb292-8e0c-11e5-8285-4af40999cf32.png)

(and a demo is here 
http://plugins.krajee.com/file-preview-icons-demo 
the upload button shows after hitting browse)

and i would like to get that "uploading" function
and trigger it manually by attaching it (as a method..?) to my own button...

maybe you have a solution... or practical tips for me like the "f12 inspect element".. but for this one...
thanks!

**Comment by kartik-v** [comment]
Please report issues in the right repo and not at various other places. You can post help for code or programming in the discussion section of the site. For your query You can go through the methods section of the docs and use the upload method to example. It depends on how u configure the plugin with Ajax or without it.

**Comment by joomlaA1** [comment]
hey @kartik-v  thanks and sry...
the methods and options section are great!! thanks...

**Comment by TAiS46** [comment]
```
$('#upload-button').click(function() {
  $('#fileinput').fileinput('upload');
});
```
