### ISSUE TITLE
i18n trait

### ISSUE THREAD

**Issue by aleksanderd** [kartik-v/yii2-krajee-base#48]
Hello!

I using date-range widget and noticed the translations do not work :(
After some debug I found, the source for 'kvdrp' category really have path to 'kvbase'.
I am not sure, but I think the trouble here:
https://github.com/kartik-v/yii2-krajee-base/blob/master/TranslationTrait.php#L45

At least if I remove the condition(by adding 'true ||') - the translations work ok for me.

Thnx!

**Comment by aleksanderd** [comment]
more accurate info:
https://github.com/kartik-v/yii2-date-range/blob/master/DateRangePicker.php#L126
here we have two calls to initI18N : 
first one with 'kvbase' category called from from InputWidget ( https://github.com/kartik-v/yii2-krajee-base/blob/master/InputWidget.php#L150 ).
so second one ( https://github.com/kartik-v/yii2-date-range/blob/master/DateRangePicker.php#L127 ) is not applied cos https://github.com/kartik-v/yii2-krajee-base/blob/master/TranslationTrait.php#L45

may be, just replace 'kvbase' with $this->_msgCat (with init value if not set to default 'kvbase') and move `$this->_msgCat = 'kvdrp';` before `parent::init();` at DateRange::init.

Thank you!

**Comment by kartik-v** [comment]
This is fixed with latest commit - will tag it after you confirm.

**Comment by aleksanderd** [comment]
all ok now, huge thnx!
