### ISSUE TITLE
Missing $pluginDestroyJs in kartik\detail\DetailView

### ISSUE THREAD

**Issue by d4rkstar** [kartik-v/yii2-krajee-base#54]
Hello,
it seems that this widget extends directly \yii\widgets\DetailView so will miss the new pluginDestroyJs attribute.

I fixed the problem adding the missing property in the WidgetTrait (this seems the most reasonable solution to me). So all the kartik widget using this trait will automatically get the missing property.

**Comment by kartik-v** [comment]
It will be resolved via DetailView update.

Note the properties are purposely not defined in trait - as it cannot be overridden in class ... [refer trait property conflict resolution](http://php.net/manual/en/language.oop5.traits.php#language.oop5.traits.properties).
