### ISSUE TITLE
Missing $pluginDestroyJs in kartik\tabs\TabsX

### ISSUE THREAD

**Issue by d4rkstar** [kartik-v/yii2-krajee-base#55]
Sorry, 
same than https://github.com/kartik-v/yii2-krajee-base/issues/54

**Comment by G1K** [comment]
Как быть чтобы использовать табы-x ?

**Comment by cavidz** [comment]
Same problem... 

Unknown Property – yii\base\UnknownPropertyException
Getting unknown property: kartik\tabs\TabsX::pluginDestroyJs

is there any solution?

**Comment by G1K** [comment]
to solve the problem I have is in the compositor prescribed, "kartik-v / yii2-krajee-base": "1.8.1"

**Comment by cavidz** [comment]
so you changed in composer.json "kartik-v / yii2-krajee-base": "1.7"  to "kartik-v / yii2-krajee-base": "1.8.1"?

**Comment by kartik-v** [comment]
You need to upgrade to latest yii2-tabs-x (release v1.2.2) -this is fixed there with other enhancements.
