### ISSUE TITLE
Plugin event listening doesn't work

### ISSUE THREAD

**Issue by mfiedorowicz** [kartik-v/yii2-krajee-base#64]
Hi Kartik,

There is a serious issue in the kv-widgets.js, it doesn't listen events at all.

Current version:

```
kvListenEvent = function (event, selector, callback) {
        var $body = $(document.body);
        if ($body.length) {
            $body.on(event, selector, callback);
        } else {
            $(selector).on(event, callback);
        }
    };
```

Working version:

```
kvListenEvent = function (event, selector, callback) {
        var $body = $(document.body);
        if ($body.length) {
            $(selector).on(event, $body, callback);
        } else {
            $(selector).on(event, callback);
        }
    };

```

Could you please release correct version?

Thank you in advance.

**Comment by kartik-v** [comment]
Note that this change has been done for #57 & #61.

This uses event delegation to a selector starting from body. So it should help in use cases where this will work even if you are rendering the selector after the event call.

**Comment by mfiedorowicz** [comment]
Thank you for quick response. The problem is that i use your sortable widget with dependency on base widget only.

**Comment by mfiedorowicz** [comment]
Maybe it wasn't clear. The problem is in line 65:

Now: 

`$body.on(event, selector, callback);
`

Proposed change: 
`$(selector).on(event, $body, callback);
`

In the current version pluginEvents are not fired at all using

```
'pluginEvents' => [
        'sortstart' => 'function() { console.log("sortstart"); }',
        'sortupdate' => 'function() { console.log("sortupdate"); }',
    ]
```

It starts working after my proposed little change. Hope it helps.

**Comment by kartik-v** [comment]
Yes it may not work for custom events like above... we should not change to what you have mentioned.

t I suppose I need to revert back to earlier state ... but it will not achieve the needs for kartik-v/yii2-widget-datetimepicker#57 & #61.
