### ISSUE TITLE
Question: jquery+bootstrap compatibility

### ISSUE THREAD

**Issue by HankBrown** [kartik-v/yii2-krajee-base#78]
RE https://react-bootstrap.github.io/getting-started.html

> Because React-Bootstrap completely re-implements the JavaScript bits of Bootstrap, it's not automatically compatible with themes that extend the default JavaScript behaviors.

Does kartik "extend the default JavaScript behaviors" ?
If I wanted to use some React-Bootstrap components, would I be jumping down a rabbit hole?

**Comment by kartik-v** [comment]
Hi it uses yii2 asset bundle features and yii inherent view JS and CSS registration methods for jquery plugins.
Not sure how you intend to use this and work with react framework. But the short answer is you can configure and use them the way you want.
