### ISSUE TITLE
Bug discovered

### ISSUE THREAD

**Issue by tklustig** [kartik-v/yii2-krajee-base#81]
Hello kartik,
one or more files of your widget ' karti-v/yii2-krajee-base' seem to have a bug **in Version v.1.8.9.**
v.1.8.8 is all right, but with version v.1.8.9, after having perforemd ' composer update' I get error like this:
`yii\base\UnknownPropertyException: Getting unknown property: kartik\tabs\TabsX::hashVarLoadPosition in E:\xampp\htdocs\yii2_perswitch\vendor\yiisoft\yii2\base\Component.php:147Stack trace:#0 E:\xampp\htdocs\yii2_perswitch\vendor\kartik-v\yii2-krajee-base\WidgetTrait.php(113): yii\base\Component->__get('hashVarLoadPosi...')#1 E:\xampp\htdocs\yii2_perswitch\vendor\kartik-v\yii2-krajee-base\WidgetTrait.php(131): kartik\tabs\TabsX->registerPluginOptions('tabsX')#2 E:\xampp\htdocs\yii2_perswitch\vendor\kartik-v\yii2-krajee-base\WidgetTrait.php(161): kartik\tabs\TabsX->getPluginScript('tabsX', 'jQuery("#w22-co...', NULL, NULL)#3 E:\xampp\htdocs\yii2_perswitch\vendor\kartik-v\yii2-tabs-x\TabsX.php(388): kartik\tabs\TabsX->registerPlugin('tabsX', 'jQuery("#w22-co...')#4 E:\xampp\htdocs\yii2_perswitch\vendor\kartik-v\yii2-tabs-x\TabsX.php(243): kartik\tabs\TabsX->registerAssets()#5 E:\xampp\htdocs\yii2_perswitch\vendor\kartik-v\yii2-tabs-x\TabsX.php(228): kartik\tabs\TabsX->initWidget()#6 E:\xampp\htdocs\yii2_perswitch\vendor\yiisoft\yii2\base\Widget.php(139): kartik\tabs\TabsX->run()#7 E:\xampp\htdocs\yii2_perswitch\frontend\modules\bewerber\views\bewerber\_expand.php(44): yii\base\Widget::widget(Array)#8 E:\xampp\htdocs\yii2_perswitch\vendor\yiisoft\yii2\base\View.php(330): require('E:\\xampp\\htdocs...')#9 E:\xampp\htdocs\yii2_perswitch\vendor\yiisoft\yii2\base\View.php(250): yii\base\View->renderPhpFile('E:\\xampp\\htdocs...', Array)#10 E:\xampp\htdocs\yii2_perswitch\vendor\yiisoft\yii2\base\View.php(152): yii\base\View->renderFile('E:\\xampp\\htdocs...', Array, Object(frontend\modules\bewerber\controllers\BewerberController))#11 E:\xampp\htdocs\yii2_perswitch\vendor\yiisoft\yii2\base\Controller.php(411): yii\base\View->render('_expand', Array, Object(frontend\modules\bewerber\controllers\BewerberController))#12 E:\xampp\htdocs\yii2_perswitch\frontend\modules\bewerber\views\bewerber\index.php(57): yii\base\Controller->renderPartial('_expand', Array)#13 [internal function]: yii\base\View->{closure}(Object(frontend\modules\bewerber\models\Bewerber), 1, 0, Object(kartik\grid\ExpandRowColumn))#14 E:\xampp\htdocs\yii2_perswitch\vendor\kartik-v\yii2-grid\ExpandRowColumn.php(241): call_user_func(Object(Closure), Object(frontend\modules\bewerber\models\Bewerber), 1, 0, Object(kartik\grid\ExpandRowColumn))#15 E:\xampp\htdocs\yii2_perswitch\vendor\kartik-v\yii2-grid\ExpandRowColumn.php(322): kartik\grid\ExpandRowColumn::parseData(Object(Closure), Object(frontend\modules\bewerber\models\Bewerber), 1, 0, Object(kartik\grid\ExpandRowColumn))#16 E:\xampp\htdocs\yii2_perswitch\vendor\yiisoft\yii2\grid\DataColumn.php(233): kartik\grid\ExpandRowColumn->getDataCellValue(Object(frontend\modules\bewerber\models\Bewerber), 1, 0)#17 E:\xampp\htdocs\yii2_perswitch\vendor\kartik-v\yii2-grid\ExpandRowColumn.php(360): yii\grid\DataColumn->renderDataCellContent(Object(frontend\modules\bewerber\models\Bewerber), 1, 0)#18 E:\xampp\htdocs\yii2_perswitch\vendor\yiisoft\yii2\grid\GridView.php(507): kartik\grid\ExpandRowColumn->renderDataCell(Object(frontend\modules\bewerber\models\Bewerber), 1, 0)#19 E:\xampp\htdocs\yii2_perswitch\vendor\yiisoft\yii2\grid\GridView.php(476): yii\grid\GridView->renderTableRow(Object(frontend\modules\bewerber\models\Bewerber), 1, 0)#20 E:\xampp\htdocs\yii2_perswitch\vendor\kartik-v\yii2-grid\GridView.php(1000): yii\grid\GridView->renderTableBody()#21 E:\xampp\htdocs\yii2_perswitch\vendor\yiisoft\yii2\grid\GridView.php(347): kartik\grid\GridView->renderTableBody()#22 E:\xampp\htdocs\yii2_perswitch\vendor\yiisoft\yii2\widgets\BaseListView.php(159): yii\grid\GridView->renderItems()#23 E:\xampp\htdocs\yii2_perswitch\vendor\yiisoft\yii2\grid\GridView.php(316): yii\widgets\BaseListView->renderSection('{items}')#24 E:\xampp\htdocs\yii2_perswitch\vendor\yiisoft\yii2\widgets\BaseListView.php(134): yii\grid\GridView->renderSection('{items}')#25 [internal function]: yii\widgets\BaseListView->yii\widgets\{closure}(Array)#26 E:\xampp\htdocs\yii2_perswitch\vendor\yiisoft\yii2\widgets\BaseListView.php(137): preg_replace_callback('/{\\w+}/', Object(Closure), '
`
Using a backup of my application with v.1.8.8 won't throw out this error. So I know, error will be caused by widget...

**Comment by kartik-v** [comment]
From the logs you shared, this is not an issue with this package but more to do with the `TabsX` extension that you are using. You need to run a composer update to get the latest release of `yii2-tabs-x` extension.
