### ISSUE TITLE
Config::getModule() does not consider nested modules

### ISSUE THREAD

**Issue by vercotux** [kartik-v/yii2-krajee-base#82]
This method is quite clever but does not consider situations where you have modules nested within modules.

* `Yii::$app` is technically a module itself (level `0`)
* `Yii::$app->getModule($m)` returns a module on the app level (level `1`) <-- the method does this

But, when we access modules through the [controller](http://www.yiiframework.com/doc-2.0/yii-base-controller.html#$module-detail), things are reversed.

`Yii::$app->controller->module` returns the *current* module, which could be on *any* level! (level `N`)

Each module also contains a [`$module`](http://www.yiiframework.com/doc-2.0/yii-base-module.html#$module-detail) property, which links to its parent module.

Therefore it is possible that the module you are looking for will be on level `N-1` or `N-2` or `N-3` ... Eg.:
* `Yii::$app->controller->module->getModule($m)` (level `N-1`) <-- the method only does this one
* `Yii::$app->controller->module->module->getModule($m)` (level `N-2`)
* `Yii::$app->controller->module->module->module->getModule($m)` (level `N-3`)
* ...

Right now the method only looks for the module at two specific levels: `1` and `N-1`. However the module could also be hiding anywhere between levels `1` and `N-1` in case of multiple nested modules. Additionally the module you are looking for could even be the current module itself (`Yii::$app->controller->module` aka level `N`).

So to overview:

Level `0` - ignored (this one is probably fine since we are specifically looking for a module not the app)
Level `1` - OK
Level `2`...`N-2` - ignored
Level `N-1` - OK
Level `N` - ignored

**Comment by kartik-v** [comment]
Need to understand your query clearly. Note that this method is designed and intended for use currently within Krajee extension and  module controllers only. If using within a module controller like say yii2-grid... It should return that module itself and does not depend on which level the module is defined ... Are you expecting it should return something else?

**Comment by kartik-v** [comment]
The difference will be if you are using this method outside a controller action in any other class.. or in any other controller outside of krajee module

**Comment by vercotux** [comment]
This is needed when one of you modules (such as yii2-dynagrid) is used inside another module (rather than in the main Yii application). Now, I don't know it that is something you want to support, but for it to work the levels `2` to `N-2` would need to be checked.

**Comment by kartik-v** [comment]
@vercotux ... just want to understand what is the enhancement expected in using the extension... if `yii2-dynagrid` is used within another module or submodule (does not matter)... this method when called from a controller action within the yii2-dynagrid module (like say `\kartik\dynagrid\controllers\SettingsController`) should automatically return that sub-sub-module (which is what is expected - are you expecting something else as a developer here).

**Comment by kartik-v** [comment]
I think the enhancement expected... will be if it is used outside of a controller action like within a widget...

**Comment by vercotux** [comment]
Sure, here is a concrete example.

In yii2-dynagrid there is a controller called [SettingsController](https://github.com/kartik-v/yii2-dynagrid/blob/master/controllers/SettingsController.php) with one action ('get-config').
If you nest yii2-dynagrid inside another module (let's call it "somemodule"), then the full path to that controller's action will become: `/somemodule/dynagrid/settings/get-action`

So when [`Config::getModule()`](https://github.com/kartik-v/yii2-dynagrid/blob/322a245d57b99e3194c0f76f6b617aef291176b0/models/DynaGridSettings.php#L250) is called in there, it will not be able to find the parent 'dynagrid' module, because it expects to find it on either level 1 (app's module) or as a submodule of the current module (`$controller->module`), which *is* the dynagrid.

**Comment by kartik-v** [comment]
For the above use case `yii2-dynagrid` provides an option for you to set the right action.

Just set `\kartik\dynagrid\Module::settingsConfigAction` to point to the right action for your use case above. This can be done either at app / module config level OR dynamically just before you render the dynagrid widget.

**Comment by vercotux** [comment]
That is exactly what I did. But it will only find the dynagrid module if it is configured on the app level, which it is not, because the whole thing is encapsulated in a standalone module, so it will assume the dynagrid module is missing.

**Comment by kartik-v** [comment]
It actually should not happen if called within `SettingsController`. The issue you face is because the `Config::getModule` is called from non-controller actions like within `kartik\dynagrid\Dynagrid` widget which in turn  you are rendering and calling from your parent controller action resulting in the issue.

**Comment by kartik-v** [comment]
I feel it should need some developer action.. but I will think about how best this can be generalized for resolution... as parent module tree traversal is not an ideal way...

Also need to consider use cases of what happens if parent module has a dynagrid configuration as well as lower level module has another dynagrid configuration - the preference will be low to up by default...

**Comment by vercotux** [comment]
I know what you are saying, but in this case it really is called from within `SettingsController`.

It is called from the DynaGridSettings model, here: https://github.com/kartik-v/yii2-dynagrid/blob/322a245d57b99e3194c0f76f6b617aef291176b0/models/DynaGridSettings.php#L250
which in turn is actually called from within `SettingsController`, right here: https://github.com/kartik-v/yii2-dynagrid/blob/322a245d57b99e3194c0f76f6b617aef291176b0/controllers/SettingsController.php#L37

**Comment by kartik-v** [comment]
> which in turn is actually called from within `SettingsController`

will check on this...

**Comment by kartik-v** [comment]
> which in turn is actually called from within `SettingsController`

`Yii::$app->controller->module` will always return the module the controller belongs to --- [refer here](https://github.com/yiisoft/yii2/blob/master/framework/base/Controller.php#L46) 

It does not return the child module like `Yii::$app->getModule` does ... 

so from `SettingsController` action you should ideally get the dynagrid module where that controller belongs to... so I still wonder why you are facing an issue

**Comment by vercotux** [comment]
Because in that case `Yii::$app->controller->module` returns dynagrid itself. And `Config::getModule()` is trying to find it at `Yii::$app->controller->module->getModule('dynagrid')` which will of course be null.

**Comment by kartik-v** [comment]
Ok will check a way to set this up... a bit better.

**Comment by kartik-v** [comment]
I have provided a fix but not tested. Check if this works fine and let know (and will reopen).

**Comment by vercotux** [comment]
Confirming, this works. Beautiful. :heart:
