### ISSUE TITLE
I just start to get this error "Trait 'kartik\base\BootstrapTrait' not found"

### ISSUE THREAD

**Issue by mavelar** [kartik-v/yii2-krajee-base#89]

**Comment by kartik-v** [comment]
Check your app installation and update your app packages via composer. The class [`BootstrapTrait` exists in this repo](https://github.com/kartik-v/yii2-krajee-base/blob/master/src/BootstrapTrait.php).

**Comment by abdallah-elsabeeh** [comment]
Dear @kartik-v  we face the same problem i did composer update in 1 spirit machines with the same error 
so i update the php version to 7 to solve the trait issue
