### ISSUE TITLE
JS errors after upgrading of yii2-krajee-base

### ISSUE THREAD

**Issue by sptik12** [kartik-v/yii2-krajee-base#93]
After executing composer update our yii2-krajee-base package was updated form 1.8.9 to 1.9.2 and we 
lost ability to use kartik-v/yii2-dialog extension along with your select2, datetime and some other external components (such as yii2-slick-carousel).

After upgrading we got a lots of java script errors.

yii2-dialog is included as
echo Dialog::widget(['overrideYiiConfirm' => true]);
or
echo Dialog::widget([
	'libName' => 'krajeeDialogCust',
	'options' => ['draggable' => true, 'closable' => true, 'buttons' => false],
]);
 
We checked  sources and found that when dialog extension is used
 jquery.js is included twice  by some reason - in the head and in the top, it cause js errors .

It seems the reason of that is specifying of POS_HEAD position in DialogAsset.php in yii2-dialog.
We see the following string in it: $jsOptions = ['position' => View::POS_HEAD];

 Can you check this issue?

Thank you very much! Your components are great!

**Comment by kartik-v** [comment]
You could control the position of loading of js via `Dialog::jsPosition`. Anyway this is to do with `yii2-dialog` which is being enhanced for Bootstrap 4.x and will be fixed there.
