### ISSUE TITLE
'kartik\export\ExportMenu and kartik\base\TranslationTrait define the same property ($_msgCat)

### ISSUE THREAD

**Issue by peresz** [kartik-v/yii2-krajee-base#97]
After upgrading krejee-base from 1.9.3 to 1.9.4 error appears in log and part of application stop working:

_2018-09-06 09:07:42 [172.28.66.160][splpos][0dfs0doisd7oumctip13kbok67][error][yii\base\ErrorException:64] exception 'yii\base\ErrorException' with message 'kartik\export\ExportMenu and kartik\base\TranslationTrait define the same property ($_msgCat) in the composition of kartik\export\ExportMenu. However, the definition differs and is considered incompatible. Class was composed' in /var/www/html/events/vendor/kartik-v/yii2-export/ExportMenu.php:2012_

kartik-v/yii2-export             v1.2.9

**Comment by akorinek** [comment]
Same problem with tabs-x

**Comment by phrakon** [comment]
the same issue
`kartik\file\FileInput and kartik\base\TranslationTrait define the same property ($i18n) in the composition of kartik\file\FileInput. However, the definition differs and is considered incompatible. Class was composed`

**Comment by kartik-v** [comment]
Folks... the extensions all have been updated and enhanced - including yii2-krajee-base and tabs-x and others... few of the extensions are still in `dev-master` and will be tagged as stable releases soon. Till then check your dependencies and get the latest releases via composer (OR use the earlier stable release if you have an issue loading dev-master versions).
